### ISSUE TITLE
Use TypeScript/Flow notation

### ISSUE THREAD

**Issue by rauschma** [abozhilov/ES-Iter#9]
For documenting, I prefer:

```js
foo(start, end, step?)
```

Instead of:

```js
foo(start, end[, step])
```

This is what I’d do myself, but, incidentally, it is also what TypeScript and Flow use. I generally find their notation easy to understand.

**Comment by rauschma** [comment]
Addendum – If there are default values, then those are even better for describing the signature of a function or method:

```js
foo(start, end, step=1)
```

**Comment by abozhilov** [comment]
Thanks! I modified the spec accordingly.
